//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  Deductions from income
 * 
 * <p>Java class for DeductUndChapVIAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeductUndChapVIAType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Section80C">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80CCC">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80CCDEmployeeOrSE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80CCDEmployer">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80CCD1B">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="50000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80D">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="60000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80DD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="125000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80DDB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="80000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80E">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80EE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="50000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80G">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80GG">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="60000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80GGC">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80U">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="125000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80RRB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="300000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80QQB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="300000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80CCG">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="25000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section80TTA">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *               &lt;maxInclusive value="10000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotalChapVIADeductions">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeductUndChapVIAType", propOrder = {
    "section80C",
    "section80CCC",
    "section80CCDEmployeeOrSE",
    "section80CCDEmployer",
    "section80CCD1B",
    "section80D",
    "section80DD",
    "section80DDB",
    "section80E",
    "section80EE",
    "section80G",
    "section80GG",
    "section80GGC",
    "section80U",
    "section80RRB",
    "section80QQB",
    "section80CCG",
    "section80TTA",
    "totalChapVIADeductions"
})
public class DeductUndChapVIAType {

    @XmlElement(name = "Section80C", required = true)
    protected BigInteger section80C;
    @XmlElement(name = "Section80CCC", required = true)
    protected BigInteger section80CCC;
    @XmlElement(name = "Section80CCDEmployeeOrSE", defaultValue = "0")
    protected BigInteger section80CCDEmployeeOrSE;
    @XmlElement(name = "Section80CCDEmployer", required = true)
    protected BigInteger section80CCDEmployer;
    @XmlElement(name = "Section80CCD1B")
    protected BigInteger section80CCD1B;
    @XmlElement(name = "Section80D")
    protected BigInteger section80D;
    @XmlElement(name = "Section80DD")
    protected BigInteger section80DD;
    @XmlElement(name = "Section80DDB")
    protected BigInteger section80DDB;
    @XmlElement(name = "Section80E", required = true)
    protected BigInteger section80E;
    @XmlElement(name = "Section80EE", defaultValue = "0")
    protected BigInteger section80EE;
    @XmlElement(name = "Section80G", required = true)
    protected BigInteger section80G;
    @XmlElement(name = "Section80GG")
    protected BigInteger section80GG;
    @XmlElement(name = "Section80GGC", required = true)
    protected BigInteger section80GGC;
    @XmlElement(name = "Section80U")
    protected BigInteger section80U;
    @XmlElement(name = "Section80RRB")
    protected BigInteger section80RRB;
    @XmlElement(name = "Section80QQB")
    protected BigInteger section80QQB;
    @XmlElement(name = "Section80CCG")
    protected BigInteger section80CCG;
    @XmlElement(name = "Section80TTA")
    protected BigInteger section80TTA;
    @XmlElement(name = "TotalChapVIADeductions", required = true)
    protected BigInteger totalChapVIADeductions;

    /**
     * Gets the value of the section80C property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSection80C() {
        return section80C;
    }

    /**
     * Sets the value of the section80C property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSection80C(BigInteger value) {
        this.section80C = value;
    }

    /**
     * Gets the value of the section80CCC property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSection80CCC() {
        return section80CCC;
    }

    /**
     * Sets the value of the section80CCC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSection80CCC(BigInteger value) {
        this.section80CCC = value;
    }

    /**
     * Gets the value of the section80CCDEmployeeOrSE property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSection80CCDEmployeeOrSE() {
        return section80CCDEmployeeOrSE;
    }

    /**
     * Sets the value of the section80CCDEmployeeOrSE property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSection80CCDEmployeeOrSE(BigInteger value) {
        this.section80CCDEmployeeOrSE = value;
    }

    /**
     * Gets the value of the section80CCDEmployer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSection80CCDEmployer() {
        return section80CCDEmployer;
    }

    /**
     * Sets the value of the section80CCDEmployer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSection80CCDEmployer(BigInteger value) {
        this.section80CCDEmployer = value;
    }

    /**
     * Gets the value of the section80CCD1B property.
     * 
     */
    public BigInteger getSection80CCD1B() {
        return section80CCD1B;
    }

    /**
     * Sets the value of the section80CCD1B property.
     * 
     */
    public void setSection80CCD1B(BigInteger value) {
        this.section80CCD1B = value;
    }

    /**
     * Gets the value of the section80D property.
     * 
     */
    public BigInteger getSection80D() {
        return section80D;
    }

    /**
     * Sets the value of the section80D property.
     * 
     */
    public void setSection80D(BigInteger value) {
        this.section80D = value;
    }

    /**
     * Gets the value of the section80DD property.
     * 
     */
    public BigInteger getSection80DD() {
        return section80DD;
    }

    /**
     * Sets the value of the section80DD property.
     * 
     */
    public void setSection80DD(BigInteger value) {
        this.section80DD = value;
    }

    /**
     * Gets the value of the section80DDB property.
     * 
     */
    public BigInteger getSection80DDB() {
        return section80DDB;
    }

    /**
     * Sets the value of the section80DDB property.
     * 
     */
    public void setSection80DDB(BigInteger value) {
        this.section80DDB = value;
    }

    /**
     * Gets the value of the section80E property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSection80E() {
        return section80E;
    }

    /**
     * Sets the value of the section80E property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSection80E(BigInteger value) {
        this.section80E = value;
    }

    /**
     * Gets the value of the section80EE property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public BigInteger getSection80EE() {
        return section80EE;
    }

    /**
     * Sets the value of the section80EE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSection80EE(BigInteger value) {
        this.section80EE = value;
    }

    /**
     * Gets the value of the section80G property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSection80G() {
        return section80G;
    }

    /**
     * Sets the value of the section80G property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSection80G(BigInteger value) {
        this.section80G = value;
    }

    /**
     * Gets the value of the section80GG property.
     * 
     */
    public BigInteger getSection80GG() {
        return section80GG;
    }

    /**
     * Sets the value of the section80GG property.
     * 
     */
    public void setSection80GG(BigInteger value) {
        this.section80GG = value;
    }

    /**
     * Gets the value of the section80GGC property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSection80GGC() {
        return section80GGC;
    }

    /**
     * Sets the value of the section80GGC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSection80GGC(BigInteger value) {
        this.section80GGC = value;
    }

    /**
     * Gets the value of the section80U property.
     * 
     */
    public BigInteger getSection80U() {
        return section80U;
    }

    /**
     * Sets the value of the section80U property.
     * 
     */
    public void setSection80U(BigInteger value) {
        this.section80U = value;
    }

    /**
     * Gets the value of the section80RRB property.
     * 
     */
    public BigInteger getSection80RRB() {
        return section80RRB;
    }

    /**
     * Sets the value of the section80RRB property.
     * 
     */
    public void setSection80RRB(BigInteger value) {
        this.section80RRB = value;
    }

    /**
     * Gets the value of the section80QQB property.
     * 
     */
    public BigInteger getSection80QQB() {
        return section80QQB;
    }

    /**
     * Sets the value of the section80QQB property.
     * 
     */
    public void setSection80QQB(BigInteger value) {
        this.section80QQB = value;
    }

    /**
     * Gets the value of the section80CCG property.
     * 
     */
    public BigInteger getSection80CCG() {
        return section80CCG;
    }

    /**
     * Sets the value of the section80CCG property.
     * 
     */
    public void setSection80CCG(BigInteger value) {
        this.section80CCG = value;
    }

    /**
     * Gets the value of the section80TTA property.
     * 
     */
    public BigInteger getSection80TTA() {
        return section80TTA;
    }

    /**
     * Sets the value of the section80TTA property.
     * 
     */
    public void setSection80TTA(BigInteger value) {
        this.section80TTA = value;
    }

    /**
     * Gets the value of the totalChapVIADeductions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalChapVIADeductions() {
        return totalChapVIADeductions;
    }

    /**
     * Sets the value of the totalChapVIADeductions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalChapVIADeductions(BigInteger value) {
        this.totalChapVIADeductions = value;
    }

}
