//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.14 at 03:31:43 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DtlsOfTransDurPrevYr", propOrder = {
    "name",
    "addressCT",
    "pan",
    "natureOfTrans",
    "aggAmount"
})
public class DtlsOfTransDurPrevYr {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "AddressCT", required = true)
    protected AddressCT addressCT;
    @XmlElement(name = "Pan", required = true)
    protected String pan;
    @XmlElement(name = "NatureOfTrans", required = true)
    protected String natureOfTrans;
    @XmlElement(name = "AggAmount", required = true)
    protected BigInteger aggAmount;

    
    public String getNatureOfTrans() {
		return natureOfTrans;
	}


	public void setNatureOfTrans(String natureOfTrans) {
		this.natureOfTrans = natureOfTrans;
	}


	public BigInteger getAggAmount() {
		return aggAmount;
	}


	public void setAggAmount(BigInteger aggAmount) {
		this.aggAmount = aggAmount;
	}


	public String getName() {
        return name;
    }

   
    public void setName(String value) {
        this.name = value;
    }

   
    public AddressCT getAddressCT() {
        return addressCT;
    }

 
    public void setAddressCT(AddressCT value) {
        this.addressCT = value;
    }

   
    public String getPan() {
        return pan;
    }

  
    public void setPan(String value) {
        this.pan = value;
    }

   
    

}
