//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import com.itd.efiling.offline.common.jaxb.adapters.DateAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DesigOfficerWardorCircle" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;maxLength value="75"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReturnFileSec">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *               &lt;totalDigits value="2"/>
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="13"/>
 *               &lt;enumeration value="14"/>
 *               &lt;enumeration value="15"/>
 *               &lt;enumeration value="16"/>
 *               &lt;enumeration value="17"/>
 *               &lt;enumeration value="18"/>
 *               &lt;enumeration value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AckNoOriginalReturn" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="15"/>
 *               &lt;pattern value="[0-9]{15}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NoticeNo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;maxLength value="23"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DefRetOrigRetFiledDate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *               &lt;minInclusive value="2018-04-01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReturnType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="O"/>
 *               &lt;enumeration value="R"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReceiptNo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="15"/>
 *               &lt;pattern value="[0-9]{15}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OrigRetFiledDate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *               &lt;minInclusive value="2018-04-01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ResidentialStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;maxLength value="3"/>
 *               &lt;enumeration value="RES"/>
 *               &lt;enumeration value="NRI"/>
 *               &lt;enumeration value="NOR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TaxStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;enumeration value="TR"/>
 *               &lt;enumeration value="TP"/>
 *               &lt;enumeration value="NT"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PortugeseCC5A" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;length value="1"/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PANOfSpouse" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;length value="10"/>
 *               &lt;pattern value="[A-Z][A-Z][A-Z][P][A-Z]\d\d\d\d[A-Z]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NoticeDateUnderSec" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *               &lt;minInclusive value="2018-04-01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "desigOfficerWardorCircle",
    "returnFileSec",
    "ackNoOriginalReturn",
    "noticeNo",
    "defRetOrigRetFiledDate",
    "returnType",
    "receiptNo",
    "origRetFiledDate",
    "residentialStatus",
    "taxStatus",
    "portugeseCC5A",
    "panOfSpouse",
    "noticeDateUnderSec"
})
@XmlRootElement(name = "FilingStatus")
public class FilingStatus {

    @XmlElement(name = "DesigOfficerWardorCircle")
    protected String desigOfficerWardorCircle;
    @XmlElement(name = "ReturnFileSec", defaultValue = "11")
    protected String returnFileSec;
    @XmlElement(name = "AckNoOriginalReturn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ackNoOriginalReturn;
    @XmlElement(name = "NoticeNo")
    protected String noticeNo;
    @XmlElement(name = "DefRetOrigRetFiledDate")
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(DateAdapter.class) 
    protected Date defRetOrigRetFiledDate;
    @XmlElement(name = "ReturnType", required = true)
    protected String returnType;
    @XmlElement(name = "ReceiptNo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String receiptNo;
    @XmlElement(name = "OrigRetFiledDate")
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(DateAdapter.class) 
    protected Date origRetFiledDate;
    @XmlElement(name = "ResidentialStatus", required = true)
    protected String residentialStatus;
    @XmlElement(name = "TaxStatus", required = true)
    protected String taxStatus;
    @XmlElement(name = "PortugeseCC5A")
    protected String portugeseCC5A;
    @XmlElement(name = "PANOfSpouse")
    protected String panOfSpouse;
    @XmlElement(name = "NoticeDateUnderSec", required = true)
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(DateAdapter.class)  
    protected Date noticeDateUnderSec;
   
    
    @XmlTransient
    protected String residentialStatusfirm;
    /**
     * Gets the value of the desigOfficerWardorCircle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesigOfficerWardorCircle() {
        return desigOfficerWardorCircle;
    }

    /**
     * Sets the value of the desigOfficerWardorCircle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesigOfficerWardorCircle(String value) {
        this.desigOfficerWardorCircle = value;
    }

    /**
     * Gets the value of the returnFileSec property.
     * 
     */
  

    /**
     * Gets the value of the ackNoOriginalReturn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAckNoOriginalReturn() {
        return ackNoOriginalReturn;
    }

    public String getReturnFileSec() {
		return returnFileSec;
	}

	public void setReturnFileSec(String returnFileSec) {
		this.returnFileSec = returnFileSec;
	}

	public String getPanOfSpouse() {
		return panOfSpouse;
	}

	public void setPanOfSpouse(String panOfSpouse) {
		this.panOfSpouse = panOfSpouse;
	}

	/**
     * Sets the value of the ackNoOriginalReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAckNoOriginalReturn(String value) {
        this.ackNoOriginalReturn = value;
    }

    /**
     * Gets the value of the noticeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoticeNo() {
        return noticeNo;
    }

    /**
     * Sets the value of the noticeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoticeNo(String value) {
        this.noticeNo = value;
    }

    /**
     * Gets the value of the defRetOrigRetFiledDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
   

    /**
     * Gets the value of the returnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnType() {
        return returnType;
    }

    /**
     * Sets the value of the returnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnType(String value) {
        this.returnType = value;
    }

    /**
     * Gets the value of the receiptNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptNo() {
        return receiptNo;
    }

    /**
     * Sets the value of the receiptNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptNo(String value) {
        this.receiptNo = value;
    }

    /**
     * Gets the value of the origRetFiledDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
   

    /**
     * Gets the value of the residentialStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidentialStatus() {
        return residentialStatus;
    }

    public Date getDefRetOrigRetFiledDate() {
		return defRetOrigRetFiledDate;
	}

	public void setDefRetOrigRetFiledDate(Date defRetOrigRetFiledDate) {
		this.defRetOrigRetFiledDate = defRetOrigRetFiledDate;
	}

	public Date getOrigRetFiledDate() {
		return origRetFiledDate;
	}

	public void setOrigRetFiledDate(Date origRetFiledDate) {
		this.origRetFiledDate = origRetFiledDate;
	}

	/**
     * Sets the value of the residentialStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidentialStatus(String value) {
        this.residentialStatus = value;
    }

    /**
     * Gets the value of the taxStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxStatus() {
        return taxStatus;
    }

    /**
     * Sets the value of the taxStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxStatus(String value) {
        this.taxStatus = value;
    }

    /**
     * Gets the value of the portugeseCC5A property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortugeseCC5A() {
        return portugeseCC5A;
    }

    /**
     * Sets the value of the portugeseCC5A property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortugeseCC5A(String value) {
        this.portugeseCC5A = value;
    }

    /**
     * Gets the value of the panOfSpouse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPANOfSpouse() {
        return panOfSpouse;
    }

    /**
     * Sets the value of the panOfSpouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPANOfSpouse(String value) {
        this.panOfSpouse = value;
    }

    /**
     * Gets the value of the noticeDateUnderSec property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getNoticeDateUnderSec() {
        return noticeDateUnderSec;
    }

    /**
     * Sets the value of the noticeDateUnderSec property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNoticeDateUnderSec(Date value) {
        this.noticeDateUnderSec = value;
    }

	public String getResidentialStatusfirm() {
		return residentialStatusfirm;
	}

	public void setResidentialStatusfirm(String residentialStatusfirm) {
		this.residentialStatusfirm = residentialStatusfirm;
	}

	
}
