//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterestHeldInaAsset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterestHeldInaAsset">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NameOfFirm">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/master}AddressAL"/>
 *         &lt;element name="PanOfFirm">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;pattern value="[A-Z][A-Z][A-Z][A-Z][A-Z]\d\d\d\d[A-Z]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AssesseInvestment">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterestHeldInaAsset", propOrder = {
    "nameOfFirm",
    "addressAL",
    "panOfFirm",
    "assesseInvestment"
})
public class InterestHeldInaAsset {

    @XmlElement(name = "NameOfFirm", required = true)
    protected String nameOfFirm;
    @XmlElement(name = "AddressAL", required = true)
    protected AddressAL addressAL;
    @XmlElement(name = "PanOfFirm", required = true)
    protected String panOfFirm;
    @XmlElement(name = "AssesseInvestment", required = true)
    protected BigInteger assesseInvestment;

    /**
     * Gets the value of the nameOfFirm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfFirm() {
        return nameOfFirm;
    }

    /**
     * Sets the value of the nameOfFirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfFirm(String value) {
        this.nameOfFirm = value;
    }

    /**
     *  Address of assesee in Sch AL
     * 
     * @return
     *     possible object is
     *     {@link AddressAL }
     *     
     */
    public AddressAL getAddressAL() {
        return addressAL;
    }

    /**
     * Sets the value of the addressAL property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressAL }
     *     
     */
    public void setAddressAL(AddressAL value) {
        this.addressAL = value;
    }

    /**
     * Gets the value of the panOfFirm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPanOfFirm() {
        return panOfFirm;
    }

    /**
     * Sets the value of the panOfFirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPanOfFirm(String value) {
        this.panOfFirm = value;
    }

    /**
     * Gets the value of the assesseInvestment property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAssesseInvestment() {
        return assesseInvestment;
    }

    /**
     * Sets the value of the assesseInvestment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAssesseInvestment(BigInteger value) {
        this.assesseInvestment = value;
    }

}
