//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IntrstPayUs234A">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IntrstPayUs234B">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IntrstPayUs234C">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LateFilingFee234F">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "intrstPayUs234A",
    "intrstPayUs234B",
    "intrstPayUs234C",
    "lateFilingFee234F"
})
@XmlRootElement(name = "IntrstPay")
public class IntrstPay {

    @XmlElement(name = "IntrstPayUs234A", required = true, defaultValue = "0")
    protected BigInteger intrstPayUs234A;
    @XmlElement(name = "IntrstPayUs234B", required = true, defaultValue = "0")
    protected BigInteger intrstPayUs234B;
    @XmlElement(name = "IntrstPayUs234C", required = true, defaultValue = "0")
    protected BigInteger intrstPayUs234C;
    @XmlElement(name = "LateFilingFee234F", required = true, defaultValue = "0")
    protected BigInteger lateFilingFee234F;

    /**
     * Gets the value of the intrstPayUs234A property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIntrstPayUs234A() {
        return intrstPayUs234A;
    }

    /**
     * Sets the value of the intrstPayUs234A property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIntrstPayUs234A(BigInteger value) {
        this.intrstPayUs234A = value;
    }

    /**
     * Gets the value of the intrstPayUs234B property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIntrstPayUs234B() {
        return intrstPayUs234B;
    }

    /**
     * Sets the value of the intrstPayUs234B property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIntrstPayUs234B(BigInteger value) {
        this.intrstPayUs234B = value;
    }

    /**
     * Gets the value of the intrstPayUs234C property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIntrstPayUs234C() {
        return intrstPayUs234C;
    }

    /**
     * Sets the value of the intrstPayUs234C property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIntrstPayUs234C(BigInteger value) {
        this.intrstPayUs234C = value;
    }

    /**
     * Gets the value of the lateFilingFee234F property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLateFilingFee234F() {
        return lateFilingFee234F;
    }

    /**
     * Sets the value of the lateFilingFee234F property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLateFilingFee234F(BigInteger value) {
        this.lateFilingFee234F = value;
    }

}
