//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"incomeFromBusinessProf",
	    "salary",
	    "alwnsNotExempt",
	    "perquisitesValue",
	    "profitsInSalary",
	    "deductionUs16",
	    "incomeFromSal",
	    "typeOfHP",
	    "grossRentReceived",
	    "taxPaidlocalAuth",
	    "annualValue",
	    "standardDeduction",
	    "interestPayable",
	    "totalIncomeOfHP",
	    "incomeOthSrc",
	    "grossTotIncome",
	    "usrDeductUndChapVIA",
	    "deductUndChapVIAType",
	    "totalIncome"
})
@XmlRootElement(name = "IncomeDeductions")
public class ITR4IncomeDeductions {

    @XmlElement(name = "IncomeFromBusinessProf", defaultValue = "0")
    protected BigInteger incomeFromBusinessProf;
    @XmlElement(name = "Salary",defaultValue = "0")
    protected BigInteger salary;
    @XmlElement(name = "AlwnsNotExempt",defaultValue = "0")
    protected BigInteger alwnsNotExempt;
    @XmlElement(name = "PerquisitesValue",defaultValue = "0")
    protected BigInteger perquisitesValue;
    @XmlElement(name = "ProfitsInSalary",defaultValue = "0")
    protected BigInteger profitsInSalary;
    @XmlElement(name = "DeductionUs16",defaultValue = "0")
    protected BigInteger deductionUs16;
    @XmlElement(name = "IncomeFromSal", defaultValue = "0")
    protected BigInteger incomeFromSal;
    @XmlElement(name = "TypeOfHP")
    protected String typeOfHP;
    @XmlElement(name = "GrossRentReceived",defaultValue = "0")
    protected BigInteger grossRentReceived;
    @XmlElement(name = "TaxPaidlocalAuth",defaultValue = "0")
    protected BigInteger taxPaidlocalAuth;
    @XmlElement(name = "AnnualValue",defaultValue = "0")
    protected BigInteger annualValue;
    @XmlElement(name = "AnnualValue30Percent",defaultValue = "0")
    protected BigInteger standardDeduction;
    @XmlElement(name = "InterestPayable",defaultValue = "0")
    protected BigInteger interestPayable;
    @XmlElement(name = "TotalIncomeOfHP", defaultValue = "0")
    protected BigInteger totalIncomeOfHP;
    @XmlElement(name = "IncomeOthSrc", defaultValue = "0")
    protected BigInteger incomeOthSrc;
    @XmlElement(name = "GrossTotIncome", defaultValue = "0")
    protected BigInteger grossTotIncome;
    @XmlElement(name = "UsrDeductUndChapVIA", required = true)
    protected UsrDeductUndChapVIAType usrDeductUndChapVIA;
    @XmlElement(name = "DeductUndChapVIA", required = true)
    protected DeductUndChapVIAType deductUndChapVIAType;
    @XmlElement(name = "TotalIncome", required = true, defaultValue = "0")
    protected BigInteger totalIncome;

  
    public BigInteger getIncomeFromBusinessProf() {
        return incomeFromBusinessProf;
    }

   
    public void setIncomeFromBusinessProf(BigInteger value) {
        this.incomeFromBusinessProf = value;
    }

  
    public BigInteger getIncomeFromSal() {
        return incomeFromSal;
    }

    public void setIncomeFromSal(BigInteger value) {
        this.incomeFromSal = value;
    }

    public String getTypeOfHP() {
        return typeOfHP;
    }


    public void setTypeOfHP(String value) {
        this.typeOfHP = value;
    }

 
    public BigInteger getTotalIncomeOfHP() {
        return totalIncomeOfHP;
    }

 
    public void setTotalIncomeOfHP(BigInteger value) {
        this.totalIncomeOfHP = value;
    }

 
    public BigInteger getIncomeOthSrc() {
        return incomeOthSrc;
    }

 
    public void setIncomeOthSrc(BigInteger value) {
        this.incomeOthSrc = value;
    }

 
    public BigInteger getGrossTotIncome() {
        return grossTotIncome;
    }

  
    public void setGrossTotIncome(BigInteger value) {
        this.grossTotIncome = value;
    }

 
    public UsrDeductUndChapVIAType getUsrDeductUndChapVIA() {
        return usrDeductUndChapVIA;
    }

 
    public void setUsrDeductUndChapVIA(UsrDeductUndChapVIAType value) {
        this.usrDeductUndChapVIA = value;
    }

  
 

  
    public BigInteger getTotalIncome() {
        return totalIncome;
    }

    public DeductUndChapVIAType getDeductUndChapVIAType() {
		return deductUndChapVIAType;
	}

	public void setDeductUndChapVIAType(DeductUndChapVIAType deductUndChapVIAType) {
		this.deductUndChapVIAType = deductUndChapVIAType;
	}


    public void setTotalIncome(BigInteger value) {
        this.totalIncome = value;
    }

	public BigInteger getSalary() {
		return salary;
	}

	public void setSalary(BigInteger salary) {
		this.salary = salary;
	}

	public BigInteger getAlwnsNotExempt() {
		return alwnsNotExempt;
	}

	public void setAlwnsNotExempt(BigInteger alwnsNotExempt) {
		this.alwnsNotExempt = alwnsNotExempt;
	}

	public BigInteger getPerquisitesValue() {
		return perquisitesValue;
	}

	public void setPerquisitesValue(BigInteger perquisitesValue) {
		this.perquisitesValue = perquisitesValue;
	}

	public BigInteger getProfitsInSalary() {
		return profitsInSalary;
	}

	public void setProfitsInSalary(BigInteger profitsInSalary) {
		this.profitsInSalary = profitsInSalary;
	}

	public BigInteger getDeductionUs16() {
		return deductionUs16;
	}

	public void setDeductionUs16(BigInteger deductionUs16) {
		this.deductionUs16 = deductionUs16;
	}

	public BigInteger getGrossRentReceived() {
		return grossRentReceived;
	}

	public void setGrossRentReceived(BigInteger grossRentReceived) {
		this.grossRentReceived = grossRentReceived;
	}

	public BigInteger getTaxPaidlocalAuth() {
		return taxPaidlocalAuth;
	}

	public void setTaxPaidlocalAuth(BigInteger taxPaidlocalAuth) {
		this.taxPaidlocalAuth = taxPaidlocalAuth;
	}

	public BigInteger getAnnualValue() {
		return annualValue;
	}

	public void setAnnualValue(BigInteger annualValue) {
		this.annualValue = annualValue;
	}

	public BigInteger getStandardDeduction() {
		return standardDeduction;
	}

	public void setStandardDeduction(BigInteger standardDeduction) {
		this.standardDeduction = standardDeduction;
	}

	public BigInteger getInterestPayable() {
		return interestPayable;
	}

	public void setInterestPayable(BigInteger interestPayable) {
		this.interestPayable = interestPayable;
	}



	
    
    
}
