//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.14 at 03:31:43 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partnerMemberOwnCapital",
    "totSecuredLoans",
    "totUnSecuredLoans",
    "totAdvances",
    "totSundryCreditors",
    "totOthrCurrLiab",
    "totSrcOfFunds",
    "fixedAssets",
    "inventories",
    "sundryDebtors",
    "balWithBanks",
    "totCashInHand",
    "loansAndAdvances",
    "otherAssets",
    "totApplnOfFunds"
})
@XmlRootElement(name = "NoBooksOfAccBS")
public class NoBooksOfAccBS {

	
    @XmlElement(name = "PartnerMemberOwnCapital" ,defaultValue = "0")
    protected BigInteger partnerMemberOwnCapital;
    @XmlElement(name = "SecuredLoans",  defaultValue = "0")
    protected BigInteger totSecuredLoans;
    @XmlElement(name = "UnSecuredLoans",defaultValue = "0")
    protected BigInteger totUnSecuredLoans;
    @XmlElement(name = "Advances", defaultValue = "0")
    protected BigInteger totAdvances;
    @XmlElement(name = "SundryCreditors", defaultValue = "0")
    protected BigInteger totSundryCreditors;
    @XmlElement(name = "OthrCurrLiab", defaultValue = "0")
    protected BigInteger totOthrCurrLiab;
    @XmlElement(name = "TotCapLiabilities",  defaultValue = "0")
    protected BigInteger totSrcOfFunds;
    @XmlElement(name = "FixedAssets", defaultValue = "0")
    protected BigInteger fixedAssets;
    @XmlElement(name = "Inventories", defaultValue = "0")
    protected BigInteger inventories;
    @XmlElement(name = "SundryDebtors",  defaultValue = "0")
    protected BigInteger sundryDebtors;
    @XmlElement(name = "BalWithBanks", defaultValue = "0")
    protected BigInteger balWithBanks;
    @XmlElement(name = "CashInHand", defaultValue = "0")
    protected BigInteger totCashInHand;
    @XmlElement(name = "LoansAndAdvances", defaultValue = "0")
    protected BigInteger loansAndAdvances;
    @XmlElement(name = "OtherAssets",defaultValue = "0")
    protected BigInteger otherAssets;
    @XmlElement(name = "TotalAssets", defaultValue = "0")
    protected BigInteger totApplnOfFunds;

    /**
     * Gets the value of the partnerMemberOwnCapital property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPartnerMemberOwnCapital() {
        return partnerMemberOwnCapital;
    }

    /**
     * Sets the value of the partnerMemberOwnCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPartnerMemberOwnCapital(BigInteger value) {
        this.partnerMemberOwnCapital = value;
    }

    /**
     * Gets the value of the totSecuredLoans property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotSecuredLoans() {
        return totSecuredLoans;
    }

    /**
     * Sets the value of the totSecuredLoans property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotSecuredLoans(BigInteger value) {
        this.totSecuredLoans = value;
    }

    /**
     * Gets the value of the totUnSecuredLoans property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotUnSecuredLoans() {
        return totUnSecuredLoans;
    }

    /**
     * Sets the value of the totUnSecuredLoans property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotUnSecuredLoans(BigInteger value) {
        this.totUnSecuredLoans = value;
    }

    /**
     * Gets the value of the totAdvances property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotAdvances() {
        return totAdvances;
    }

    /**
     * Sets the value of the totAdvances property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotAdvances(BigInteger value) {
        this.totAdvances = value;
    }

    /**
     * Gets the value of the totSundryCreditors property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotSundryCreditors() {
        return totSundryCreditors;
    }

    /**
     * Sets the value of the totSundryCreditors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotSundryCreditors(BigInteger value) {
        this.totSundryCreditors = value;
    }

    /**
     * Gets the value of the totOthrCurrLiab property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotOthrCurrLiab() {
        return totOthrCurrLiab;
    }

    /**
     * Sets the value of the totOthrCurrLiab property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotOthrCurrLiab(BigInteger value) {
        this.totOthrCurrLiab = value;
    }

    /**
     * Gets the value of the totSrcOfFunds property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotSrcOfFunds() {
        return totSrcOfFunds;
    }

    /**
     * Sets the value of the totSrcOfFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotSrcOfFunds(BigInteger value) {
        this.totSrcOfFunds = value;
    }

    /**
     * Gets the value of the fixedAssets property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFixedAssets() {
        return fixedAssets;
    }

    /**
     * Sets the value of the fixedAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFixedAssets(BigInteger value) {
        this.fixedAssets = value;
    }

    /**
     * Gets the value of the inventories property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInventories() {
        return inventories;
    }

    /**
     * Sets the value of the inventories property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInventories(BigInteger value) {
        this.inventories = value;
    }

    /**
     * Gets the value of the sundryDebtors property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSundryDebtors() {
        return sundryDebtors;
    }

    /**
     * Sets the value of the sundryDebtors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSundryDebtors(BigInteger value) {
        this.sundryDebtors = value;
    }

    /**
     * Gets the value of the balWithBanks property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBalWithBanks() {
        return balWithBanks;
    }

    /**
     * Sets the value of the balWithBanks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBalWithBanks(BigInteger value) {
        this.balWithBanks = value;
    }

    /**
     * Gets the value of the totCashInHand property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotCashInHand() {
        return totCashInHand;
    }

    /**
     * Sets the value of the totCashInHand property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotCashInHand(BigInteger value) {
        this.totCashInHand = value;
    }

    /**
     * Gets the value of the loansAndAdvances property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLoansAndAdvances() {
        return loansAndAdvances;
    }

    /**
     * Sets the value of the loansAndAdvances property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLoansAndAdvances(BigInteger value) {
        this.loansAndAdvances = value;
    }

    /**
     * Gets the value of the otherAssets property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOtherAssets() {
        return otherAssets;
    }

    /**
     * Sets the value of the otherAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOtherAssets(BigInteger value) {
        this.otherAssets = value;
    }

    /**
     * Gets the value of the totApplnOfFunds property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotApplnOfFunds() {
        return totApplnOfFunds;
    }

    /**
     * Sets the value of the totApplnOfFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotApplnOfFunds(BigInteger value) {
        this.totApplnOfFunds = value;
    }

	
    
    

}
