//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotPersumInc44AE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SalInterestByFirm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotalPersumptiveInc" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IncChargeableUnderBus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totPersumInc44AE",
    "salInterestByFirm",
    "totalPersumptiveInc",
    "incChargeableUnderBus"
})
@XmlRootElement(name = "PersumptiveInc44AE")
public class PersumptiveInc44AE {

    @XmlElement(name = "TotPersumInc44AE", required = true, defaultValue = "0")
    protected BigInteger totPersumInc44AE;
    @XmlElement(name = "SalInterestByFirm")
    protected BigInteger salInterestByFirm;
    @XmlElement(name = "TotalPersumptiveInc")
    protected BigInteger totalPersumptiveInc;
    @XmlElement(name = "IncChargeableUnderBus", defaultValue = "0")
    protected BigInteger incChargeableUnderBus;

    /**
     * Gets the value of the totPersumInc44AE property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotPersumInc44AE() {
        return totPersumInc44AE;
    }

    /**
     * Sets the value of the totPersumInc44AE property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotPersumInc44AE(BigInteger value) {
        this.totPersumInc44AE = value;
    }

    /**
     * Gets the value of the salInterestByFirm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSalInterestByFirm() {
        return salInterestByFirm;
    }

    /**
     * Sets the value of the salInterestByFirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSalInterestByFirm(BigInteger value) {
        this.salInterestByFirm = value;
    }

    /**
     * Gets the value of the totalPersumptiveInc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalPersumptiveInc() {
        return totalPersumptiveInc;
    }

    /**
     * Sets the value of the totalPersumptiveInc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalPersumptiveInc(BigInteger value) {
        this.totalPersumptiveInc = value;
    }

    /**
     * Gets the value of the incChargeableUnderBus property.
     * 
     */
    public BigInteger getIncChargeableUnderBus() {
        return incChargeableUnderBus;
    }

    /**
     * Sets the value of the incChargeableUnderBus property.
     * 
     */
    public void setIncChargeableUnderBus(BigInteger value) {
        this.incChargeableUnderBus = value;
    }

}
