//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrsReceipt">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="7"/>
 *               &lt;maxInclusive value="5000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotPersumptiveInc44ADA">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "grsReceipt",
    "totPersumptiveInc44ADA"
})
@XmlRootElement(name = "PersumptiveInc44ADA")
public class PersumptiveInc44ADA {

    @XmlElement(name = "GrsReceipt", defaultValue = "0")
    protected BigInteger grsReceipt;
    @XmlElement(name = "TotPersumptiveInc44ADA", required = true, defaultValue = "0")
    protected BigInteger totPersumptiveInc44ADA;

    /**
     * Gets the value of the grsReceipt property.
     * 
     */
    public BigInteger getGrsReceipt() {
        return grsReceipt;
    }

    /**
     * Sets the value of the grsReceipt property.
     * 
     */
    public void setGrsReceipt(BigInteger value) {
        this.grsReceipt = value;
    }

    /**
     * Gets the value of the totPersumptiveInc44ADA property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotPersumptiveInc44ADA() {
        return totPersumptiveInc44ADA;
    }

    /**
     * Sets the value of the totPersumptiveInc44ADA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotPersumptiveInc44ADA(BigInteger value) {
        this.totPersumptiveInc44ADA = value;
    }

}
