//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrsTrnOverBank">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GrsTrnOverAnyOthMode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PersumptiveInc44AD6Per">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PersumptiveInc44AD8Per">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotPersumptiveInc44AD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "grsTrnOverBank",
    "grsTrnOverAnyOthMode",
    "persumptiveInc44AD6Per",
    "persumptiveInc44AD8Per",
    "totPersumptiveInc44AD"
})
@XmlRootElement(name = "PersumptiveInc44AD")
public class PersumptiveInc44AD {

    @XmlElement(name = "GrsTrnOverBank", required = true)
    protected BigInteger grsTrnOverBank;
    @XmlElement(name = "GrsTrnOverAnyOthMode", required = true)
    protected BigInteger grsTrnOverAnyOthMode;
    @XmlElement(name = "PersumptiveInc44AD6Per", required = true)
    protected BigInteger persumptiveInc44AD6Per;
    @XmlElement(name = "PersumptiveInc44AD8Per", required = true)
    protected BigInteger persumptiveInc44AD8Per;
    @XmlElement(name = "TotPersumptiveInc44AD", required = true)
    protected BigInteger totPersumptiveInc44AD;

    /**
     * Gets the value of the grsTrnOverBank property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGrsTrnOverBank() {
        return grsTrnOverBank;
    }

    /**
     * Sets the value of the grsTrnOverBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGrsTrnOverBank(BigInteger value) {
        this.grsTrnOverBank = value;
    }

    /**
     * Gets the value of the grsTrnOverAnyOthMode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGrsTrnOverAnyOthMode() {
        return grsTrnOverAnyOthMode;
    }

    /**
     * Sets the value of the grsTrnOverAnyOthMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGrsTrnOverAnyOthMode(BigInteger value) {
        this.grsTrnOverAnyOthMode = value;
    }

    /**
     * Gets the value of the persumptiveInc44AD6Per property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPersumptiveInc44AD6Per() {
        return persumptiveInc44AD6Per;
    }

    /**
     * Sets the value of the persumptiveInc44AD6Per property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPersumptiveInc44AD6Per(BigInteger value) {
        this.persumptiveInc44AD6Per = value;
    }

    /**
     * Gets the value of the persumptiveInc44AD8Per property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPersumptiveInc44AD8Per() {
        return persumptiveInc44AD8Per;
    }

    /**
     * Sets the value of the persumptiveInc44AD8Per property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPersumptiveInc44AD8Per(BigInteger value) {
        this.persumptiveInc44AD8Per = value;
    }

    /**
     * Gets the value of the totPersumptiveInc44AD property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotPersumptiveInc44AD() {
        return totPersumptiveInc44AD;
    }

    /**
     * Sets the value of the totPersumptiveInc44AD property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotPersumptiveInc44AD(BigInteger value) {
        this.totPersumptiveInc44AD = value;
    }

}
