//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RefundDue">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/master}BankAccountDtls"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refundDue",
    "bankAccountDtls"
})
@XmlRootElement(name = "Refund")
public class Refund {

    @XmlElement(name = "RefundDue", required = true, defaultValue = "0")
    protected BigInteger refundDue;
    @XmlElement(name = "BankAccountDtls", required = true)
    protected BankAccountDtls bankAccountDtls;

    /**
     * Gets the value of the refundDue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRefundDue() {
        return refundDue;
    }

    /**
     * Sets the value of the refundDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRefundDue(BigInteger value) {
        this.refundDue = value;
    }

    /**
     * Gets the value of the bankAccountDtls property.
     * 
     * @return
     *     possible object is
     *     {@link BankAccountDtls }
     *     
     */
    public BankAccountDtls getBankAccountDtls() {
        return bankAccountDtls;
    }

    /**
     * Sets the value of the bankAccountDtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankAccountDtls }
     *     
     */
    public void setBankAccountDtls(BankAccountDtls value) {
        this.bankAccountDtls = value;
    }

}
