//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/master}PersumptiveInc44AD"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/master}PersumptiveInc44ADA"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/master}PersumptiveInc44AE"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/master}NoBooksOfAccBS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "persumptiveInc44AD",
    "persumptiveInc44ADA",
    "persumptiveInc44AE",
    "turnoverGrsRcptForGST",
    "noBooksOfAccBS"
})
@XmlRootElement(name = "ScheduleBP")
public class ScheduleBP {

    @XmlElement(name = "PersumptiveInc44AD", required = true, defaultValue = "0")
    protected PersumptiveInc44AD persumptiveInc44AD;
    @XmlElement(name = "PersumptiveInc44ADA", required = true, defaultValue = "0")
    protected PersumptiveInc44ADA persumptiveInc44ADA;
    @XmlElement(name = "PersumptiveInc44AE", required = true, defaultValue = "0")
    protected PersumptiveInc44AE persumptiveInc44AE;
    @XmlElement(name = "TurnoverGrsRcptForGST")
    protected TurnoverGrsRcptForGST turnoverGrsRcptForGST;
    @XmlElement(name = "FinanclPartclrOfBusiness", required = true, defaultValue = "0")
    protected NoBooksOfAccBS noBooksOfAccBS;

    /**
     * Gets the value of the persumptiveInc44AD property.
     * 
     * @return
     *     possible object is
     *     {@link PersumptiveInc44AD }
     *     
     */
    public PersumptiveInc44AD getPersumptiveInc44AD() {
        return persumptiveInc44AD;
    }

    /**
     * Sets the value of the persumptiveInc44AD property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersumptiveInc44AD }
     *     
     */
    public void setPersumptiveInc44AD(PersumptiveInc44AD value) {
        this.persumptiveInc44AD = value;
    }

    /**
     * Gets the value of the persumptiveInc44ADA property.
     * 
     * @return
     *     possible object is
     *     {@link PersumptiveInc44ADA }
     *     
     */
    public PersumptiveInc44ADA getPersumptiveInc44ADA() {
        return persumptiveInc44ADA;
    }

    /**
     * Sets the value of the persumptiveInc44ADA property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersumptiveInc44ADA }
     *     
     */
    public void setPersumptiveInc44ADA(PersumptiveInc44ADA value) {
        this.persumptiveInc44ADA = value;
    }

    /**
     * Gets the value of the persumptiveInc44AE property.
     * 
     * @return
     *     possible object is
     *     {@link PersumptiveInc44AE }
     *     
     */
    public PersumptiveInc44AE getPersumptiveInc44AE() {
        return persumptiveInc44AE;
    }

    /**
     * Sets the value of the persumptiveInc44AE property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersumptiveInc44AE }
     *     
     */
    public void setPersumptiveInc44AE(PersumptiveInc44AE value) {
        this.persumptiveInc44AE = value;
    }

    /**
     * Gets the value of the noBooksOfAccBS property.
     * 
     * @return
     *     possible object is
     *     {@link NoBooksOfAccBS }
     *     
     */
    public NoBooksOfAccBS getNoBooksOfAccBS() {
        return noBooksOfAccBS;
    }

    /**
     * Sets the value of the noBooksOfAccBS property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoBooksOfAccBS }
     *     
     */
    public void setNoBooksOfAccBS(NoBooksOfAccBS value) {
        this.noBooksOfAccBS = value;
    }

	public TurnoverGrsRcptForGST getTurnoverGrsRcptForGST() {
		return turnoverGrsRcptForGST;
	}

	public void setTurnoverGrsRcptForGST(TurnoverGrsRcptForGST turnoverGrsRcptForGST) {
		this.turnoverGrsRcptForGST = turnoverGrsRcptForGST;
	}

}
