//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImmovableFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ImmovableDetails" type="{http://incometaxindiaefiling.gov.in/master}ImmovableDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/master}MovableAsset"/>
 *         &lt;element name="InterstAOPFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InterestHeldInaAsset" type="{http://incometaxindiaefiling.gov.in/master}InterestHeldInaAsset" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LiabilityInRelatAssets">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "immovableFlag",
    "immovableDetails",
    "movableAsset",
    "interstAOPFlag",
    "interestHeldInaAsset",
    "liabilityInRelatAssets"
})
@XmlRootElement(name = "ScheduleAL")
public class ScheduleAL {

    @XmlElement(name = "ImmovableFlag")
    protected String immovableFlag;
    @XmlElement(name = "ImmovableDetails")
    protected List<ImmovableDetails> immovableDetails;
    @XmlElement(name = "MovableAsset", required = true)
    protected MovableAsset movableAsset;
    @XmlElement(name = "InterstAOPFlag", required = true)
    protected String interstAOPFlag;
    @XmlElement(name = "InterestHeldInaAsset")
    protected List<InterestHeldInaAsset> interestHeldInaAsset;
    @XmlElement(name = "LiabilityInRelatAssets", required = true)
    protected BigInteger liabilityInRelatAssets;

    /**
     * Gets the value of the immovableFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImmovableFlag() {
        return immovableFlag;
    }

    /**
     * Sets the value of the immovableFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImmovableFlag(String value) {
        this.immovableFlag = value;
    }

    /**
     * Gets the value of the immovableDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the immovableDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImmovableDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImmovableDetails }
     * 
     * 
     */
    public List<ImmovableDetails> getImmovableDetails() {
        if (immovableDetails == null) {
            immovableDetails = new ArrayList<ImmovableDetails>();
        }
        return this.immovableDetails;
    }

    /**
     * Gets the value of the movableAsset property.
     * 
     * @return
     *     possible object is
     *     {@link MovableAsset }
     *     
     */
    public MovableAsset getMovableAsset() {
        return movableAsset;
    }

    /**
     * Sets the value of the movableAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link MovableAsset }
     *     
     */
    public void setMovableAsset(MovableAsset value) {
        this.movableAsset = value;
    }

    /**
     * Gets the value of the interstAOPFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterstAOPFlag() {
        return interstAOPFlag;
    }

    /**
     * Sets the value of the interstAOPFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterstAOPFlag(String value) {
        this.interstAOPFlag = value;
    }

    /**
     * Gets the value of the interestHeldInaAsset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interestHeldInaAsset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterestHeldInaAsset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterestHeldInaAsset }
     * 
     * 
     */
    public List<InterestHeldInaAsset> getInterestHeldInaAsset() {
        if (interestHeldInaAsset == null) {
            interestHeldInaAsset = new ArrayList<InterestHeldInaAsset>();
        }
        return this.interestHeldInaAsset;
    }

    /**
     * Gets the value of the liabilityInRelatAssets property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLiabilityInRelatAssets() {
        return liabilityInRelatAssets;
    }

    /**
     * Sets the value of the liabilityInRelatAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLiabilityInRelatAssets(BigInteger value) {
        this.liabilityInRelatAssets = value;
    }

}
