//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.24 at 04:44:44 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import com.itd.efiling.offline.common.jaxb.adapters.DateAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ScheduleGCDtls" maxOccurs="10">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RegistrationNo">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *                         &lt;maxLength value="15"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="TonnageCapacity">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *                         &lt;totalDigits value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DateOfPurchase">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CostOfAcquisition">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *                         &lt;totalDigits value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ModeofFinance">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *                         &lt;maxLength value="75"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="HoldingPeriod">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *                         &lt;totalDigits value="2"/>
 *                         &lt;minInclusive value="1"/>
 *                         &lt;maxInclusive value="12"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IncomePerVehicle">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *                         &lt;minInclusive value="7500"/>
 *                         &lt;totalDigits value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DeemedInc">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *                         &lt;minInclusive value="7500"/>
 *                         &lt;totalDigits value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scheduleGCDtls"
})
@XmlRootElement(name = "ScheduleGC")
public class ScheduleGC {

    @XmlElement(name = "ScheduleGCDtls", required = true)
    protected List<ScheduleGC.ScheduleGCDtls> scheduleGCDtls;

    /**
     * Gets the value of the scheduleGCDtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduleGCDtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduleGCDtls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScheduleGC.ScheduleGCDtls }
     * 
     * 
     */
    public List<ScheduleGC.ScheduleGCDtls> getScheduleGCDtls() {
        if (scheduleGCDtls == null) {
            scheduleGCDtls = new ArrayList<ScheduleGC.ScheduleGCDtls>();
        }
        return this.scheduleGCDtls;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RegistrationNo">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
     *               &lt;maxLength value="15"/>
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TonnageCapacity">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
     *               &lt;totalDigits value="14"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DateOfPurchase">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CostOfAcquisition">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
     *               &lt;totalDigits value="14"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ModeofFinance">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
     *               &lt;maxLength value="75"/>
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="HoldingPeriod">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
     *               &lt;totalDigits value="2"/>
     *               &lt;minInclusive value="1"/>
     *               &lt;maxInclusive value="12"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IncomePerVehicle">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
     *               &lt;minInclusive value="7500"/>
     *               &lt;totalDigits value="14"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DeemedInc">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
     *               &lt;minInclusive value="7500"/>
     *               &lt;totalDigits value="14"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "registrationNo",
        "tonnageCapacity",
        "dateOfPurchase",
        "costOfAcquisition",
        "modeofFinance",
        "holdingPeriod",
        "incomePerVehicle",
        "deemedInc"
    })
    public static class ScheduleGCDtls {

        @XmlElement(name = "RegistrationNo", required = true)
        protected String registrationNo;
        @XmlElement(name = "TonnageCapacity", required = true)
        protected BigInteger tonnageCapacity;
        @XmlElement(name = "DateOfPurchase", required = true)
        @XmlSchemaType(name = "date")
        @XmlJavaTypeAdapter(DateAdapter.class)  
        protected Date dateOfPurchase;
        @XmlElement(name = "CostOfAcquisition", required = true)
        protected BigInteger costOfAcquisition;
        @XmlElement(name = "ModeofFinance", required = true)
        protected String modeofFinance;
        @XmlElement(name = "HoldingPeriod")
        protected BigInteger holdingPeriod;
        @XmlElement(name = "IncomePerVehicle", required = true)
        protected BigInteger incomePerVehicle;
        @XmlElement(name = "DeemedInc", required = true)
        protected BigInteger deemedInc;

        /**
         * Gets the value of the registrationNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistrationNo() {
            return registrationNo;
        }

        /**
         * Sets the value of the registrationNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistrationNo(String value) {
            this.registrationNo = value;
        }

        /**
         * Gets the value of the tonnageCapacity property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTonnageCapacity() {
            return tonnageCapacity;
        }

        /**
         * Sets the value of the tonnageCapacity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTonnageCapacity(BigInteger value) {
            this.tonnageCapacity = value;
        }

         
        public Date getDateOfPurchase() {
			return dateOfPurchase;
		}

		public void setDateOfPurchase(Date dateOfPurchase) {
			this.dateOfPurchase = dateOfPurchase;
		}

		public BigInteger getCostOfAcquisition() {
            return costOfAcquisition;
        }

        /**
         * Sets the value of the costOfAcquisition property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCostOfAcquisition(BigInteger value) {
            this.costOfAcquisition = value;
        }

        /**
         * Gets the value of the modeofFinance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModeofFinance() {
            return modeofFinance;
        }

        /**
         * Sets the value of the modeofFinance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModeofFinance(String value) {
            this.modeofFinance = value;
        }

        /**
         * Gets the value of the holdingPeriod property.
         * 
         */
      

        /**
         * Gets the value of the incomePerVehicle property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIncomePerVehicle() {
            return incomePerVehicle;
        }

        public BigInteger getHoldingPeriod() {
			return holdingPeriod;
		}

		public void setHoldingPeriod(BigInteger holdingPeriod) {
			this.holdingPeriod = holdingPeriod;
		}

		/**
         * Sets the value of the incomePerVehicle property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIncomePerVehicle(BigInteger value) {
            this.incomePerVehicle = value;
        }

        /**
         * Gets the value of the deemedInc property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDeemedInc() {
            return deemedInc;
        }

        /**
         * Sets the value of the deemedInc property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDeemedInc(BigInteger value) {
            this.deemedInc = value;
        }

    }

}
