//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.16 at 01:18:01 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TDSAmountClaimed">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HeadofIncForTax">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;maxLength value="2"/>
 *               &lt;enumeration value="HP"/>
 *               &lt;enumeration value="OS"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TaxClaimedOwnHands">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ApportioningReason">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;maxLength value="3"/>
 *               &lt;enumeration value="PCC"/>
 *               &lt;enumeration value="COA"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TaxDeductDetails" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TDSAppOtherPerson">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *                         &lt;totalDigits value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="OtherPersonPAN">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *                         &lt;pattern value="[A-Z]{5}[0-9]{4}[A-Z]"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PercentageShare">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="100"/>
 *                         &lt;fractionDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IncOffered">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TDSClaimed" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IncBalCarryFrwd">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TDSBalCarryFrwd">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tdsAmountClaimed",
    "headofIncForTax",
    "taxClaimedOwnHands",
    "apportioningReason",
    "taxDeductDetails",
    "incOffered",
    "incBalCarryFrwd",
    "tdsBalCarryFrwd"
})
@XmlRootElement(name = "TDS26ASDetailsPartA")
public class TDS26ASDetailsPartA {

    @XmlElement(name = "TDSAmountClaimed", required = true)
    protected BigInteger tdsAmountClaimed;
    @XmlElement(name = "HeadofIncForTax", required = true)
    protected String headofIncForTax;
    @XmlElement(name = "TaxClaimedOwnHands", required = true)
    protected BigInteger taxClaimedOwnHands;
    @XmlElement(name = "ApportioningReason", required = true)
    protected String apportioningReason;
    @XmlElement(name = "TaxDeductDetails", required = true)
    protected List<TaxDeductDetails> taxDeductDetails;
    @XmlElement(name = "IncOffered", required = true)
    protected BigInteger incOffered;
    @XmlElement(name = "IncBalCarryFrwd", required = true)
    protected BigInteger incBalCarryFrwd;
    @XmlElement(name = "TDSBalCarryFrwd", required = true)
    protected BigInteger tdsBalCarryFrwd;
	public BigInteger getTdsAmountClaimed() {
		return tdsAmountClaimed;
	}
	public void setTdsAmountClaimed(BigInteger tdsAmountClaimed) {
		this.tdsAmountClaimed = tdsAmountClaimed;
	}
	public String getHeadofIncForTax() {
		return headofIncForTax;
	}
	public void setHeadofIncForTax(String headofIncForTax) {
		this.headofIncForTax = headofIncForTax;
	}
	public BigInteger getTaxClaimedOwnHands() {
		return taxClaimedOwnHands;
	}
	public void setTaxClaimedOwnHands(BigInteger taxClaimedOwnHands) {
		this.taxClaimedOwnHands = taxClaimedOwnHands;
	}
	public String getApportioningReason() {
		return apportioningReason;
	}
	public void setApportioningReason(String apportioningReason) {
		this.apportioningReason = apportioningReason;
	}
	public List<TaxDeductDetails> getTaxDeductDetails() {
		if (taxDeductDetails == null) {
			taxDeductDetails = new ArrayList<TaxDeductDetails>();
        }
		return taxDeductDetails;
		
	}
	public void setTaxDeductDetails(List<TaxDeductDetails> taxDeductDetails) {
		this.taxDeductDetails = taxDeductDetails;
	}
	public BigInteger getIncOffered() {
		return incOffered;
	}
	public void setIncOffered(BigInteger incOffered) {
		this.incOffered = incOffered;
	}
	public BigInteger getIncBalCarryFrwd() {
		return incBalCarryFrwd;
	}
	public void setIncBalCarryFrwd(BigInteger incBalCarryFrwd) {
		this.incBalCarryFrwd = incBalCarryFrwd;
	}
	public BigInteger getTdsBalCarryFrwd() {
		return tdsBalCarryFrwd;
	}
	public void setTdsBalCarryFrwd(BigInteger tdsBalCarryFrwd) {
		this.tdsBalCarryFrwd = tdsBalCarryFrwd;
	}

   

}
