//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.16 at 01:18:01 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AmtAppOthPANTDSClaimed">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TDSAppoOthPANClaimedSelf">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TaxDeductedPAN">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;pattern value="[A-Z]{5}[0-9]{4}[A-Z]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HeadofIncForTax">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;maxLength value="2"/>
 *               &lt;enumeration value="HP"/>
 *               &lt;enumeration value="OS"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReasonClaimOwnHands">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/master}nonEmptyString">
 *               &lt;maxLength value="3"/>
 *               &lt;enumeration value="PCC"/>
 *               &lt;enumeration value="COA"/>
 *               &lt;enumeration value="SIC"/>
 *               &lt;enumeration value="TDP"/>
 *               &lt;enumeration value="DPI"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IncOffered">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TDSClaimed">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IncBalCarryFrwd">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TDSBalCarryFrwd">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "amtAppOthPANTDSClaimed",
    "tdsAppoOthPANClaimedSelf",
    "taxDeductedPAN",
    "headofIncForTax",
    "reasonClaimOwnHands",
    "incOffered",
    "tdsClaimed",
    "incBalCarryFrwd",
    "tdsBalCarryFrwd"
})
@XmlRootElement(name = "TDS26ASDetailsPartB")
public class TDS26ASDetailsPartB {

    @XmlElement(name = "AmtAppOthPANTDSClaimed", required = true)
    protected BigInteger amtAppOthPANTDSClaimed;
    @XmlElement(name = "TDSAppoOthPANClaimedSelf", required = true)
    protected BigInteger tdsAppoOthPANClaimedSelf;
    @XmlElement(name = "TaxDeductedPAN", required = true)
    protected String taxDeductedPAN;
    @XmlElement(name = "HeadofIncForTax", required = true)
    protected String headofIncForTax;
    @XmlElement(name = "ReasonClaimOwnHands", required = true)
    protected String reasonClaimOwnHands;
    @XmlElement(name = "IncOffered", required = true)
    protected BigInteger incOffered;
    @XmlElement(name = "TDSClaimed", required = true)
    protected BigInteger tdsClaimed;
    @XmlElement(name = "IncBalCarryFrwd", required = true)
    protected BigInteger incBalCarryFrwd;
    @XmlElement(name = "TDSBalCarryFrwd", required = true)
    protected BigInteger tdsBalCarryFrwd;
	public BigInteger getAmtAppOthPANTDSClaimed() {
		return amtAppOthPANTDSClaimed;
	}
	public void setAmtAppOthPANTDSClaimed(BigInteger amtAppOthPANTDSClaimed) {
		this.amtAppOthPANTDSClaimed = amtAppOthPANTDSClaimed;
	}
	public BigInteger getTdsAppoOthPANClaimedSelf() {
		return tdsAppoOthPANClaimedSelf;
	}
	public void setTdsAppoOthPANClaimedSelf(BigInteger tdsAppoOthPANClaimedSelf) {
		this.tdsAppoOthPANClaimedSelf = tdsAppoOthPANClaimedSelf;
	}
	public String getTaxDeductedPAN() {
		return taxDeductedPAN;
	}
	public void setTaxDeductedPAN(String taxDeductedPAN) {
		this.taxDeductedPAN = taxDeductedPAN;
	}
	public String getHeadofIncForTax() {
		return headofIncForTax;
	}
	public void setHeadofIncForTax(String headofIncForTax) {
		this.headofIncForTax = headofIncForTax;
	}
	public String getReasonClaimOwnHands() {
		return reasonClaimOwnHands;
	}
	public void setReasonClaimOwnHands(String reasonClaimOwnHands) {
		this.reasonClaimOwnHands = reasonClaimOwnHands;
	}
	public BigInteger getIncOffered() {
		return incOffered;
	}
	public void setIncOffered(BigInteger incOffered) {
		this.incOffered = incOffered;
	}
	public BigInteger getTdsClaimed() {
		return tdsClaimed;
	}
	public void setTdsClaimed(BigInteger tdsClaimed) {
		this.tdsClaimed = tdsClaimed;
	}
	public BigInteger getIncBalCarryFrwd() {
		return incBalCarryFrwd;
	}
	public void setIncBalCarryFrwd(BigInteger incBalCarryFrwd) {
		this.incBalCarryFrwd = incBalCarryFrwd;
	}
	public BigInteger getTdsBalCarryFrwd() {
		return tdsBalCarryFrwd;
	}
	public void setTdsBalCarryFrwd(BigInteger tdsBalCarryFrwd) {
		this.tdsBalCarryFrwd = tdsBalCarryFrwd;
	}

    
}
