//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.20 at 08:08:15 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gstrNo",
    "amtTurnGrossRcptGST"
})
@XmlRootElement(name = "TurnoverGrsRcptForGST")
public class TurnoverGrsRcptForGST {

    @XmlElement(name = "GSTRNo")
    protected String gstrNo;
    @XmlElement(name = "AmtTurnGrossRcptGST")
    protected BigInteger amtTurnGrossRcptGST;
    
	public String getGstrNo() {
		return gstrNo;
	}
	public void setGstrNo(String gstrNo) {
		this.gstrNo = gstrNo;
	}
	public BigInteger getAmtTurnGrossRcptGST() {
		return amtTurnGrossRcptGST;
	}
	public void setAmtTurnGrossRcptGST(BigInteger amtTurnGrossRcptGST) {
		this.amtTurnGrossRcptGST = amtTurnGrossRcptGST;
	}

   
}
