//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 07:12:47 PM IST 
//


package com.itd.efiling.offline.ITR4.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsrDeductUndChapVIAType", propOrder = {
    "section80C",
    "section80CCC",
    "section80CCDEmployeeOrSE",
    "section80CCDEmployer",
    "section80CCD1B",
    "section80DHealthInsPremium",
    "section80DDUsrType",
    "section80DD",
    "section80DDBUsrType",
    "section80DDB",
    "section80E",
    "section80EE",
    "section80G",
    "section80GG",
    "section80GGC",
    "section80UUsrType",
    "section80U",
    "section80RRB",
    "section80QQB",
    "section80CCG",
    "section80TTA",
    "totalChapVIADeductions"
})
public class UsrDeductUndChapVIAType {

    @XmlElement(name = "Section80C", required = true)
    protected BigInteger section80C;
    @XmlElement(name = "Section80CCC", required = true)
    protected BigInteger section80CCC;
    @XmlElement(name = "Section80CCDEmployeeOrSE", required = true)
    protected BigInteger section80CCDEmployeeOrSE;
    @XmlElement(name = "Section80CCDEmployer", required = true)
    protected BigInteger section80CCDEmployer;
    @XmlElement(name = "Section80CCD1B", required = true)
    protected BigInteger section80CCD1B;
    @XmlElement(name = "Section80DHealthInsPremium")
    protected Section80DHealthInsPremium section80DHealthInsPremium;
    @XmlElement(name = "Section80DDUsrType")
    protected String section80DDUsrType;
    @XmlElement(name = "Section80DD", required = true)
    protected BigInteger section80DD;
    @XmlElement(name = "Section80DDBUsrType")
    protected String section80DDBUsrType;
    @XmlElement(name = "Section80DDB", required = true)
    protected BigInteger section80DDB;
    @XmlElement(name = "Section80E", required = true)
    protected BigInteger section80E;
    @XmlElement(name = "Section80EE", defaultValue = "0")
    protected BigInteger section80EE;
    @XmlElement(name = "Section80G", required = true)
    protected BigInteger section80G;
    @XmlElement(name = "Section80GG", required = true)
    protected BigInteger section80GG;
    @XmlElement(name = "Section80GGC", required = true)
    protected BigInteger section80GGC;
    @XmlElement(name = "Section80UUsrType")
    protected String section80UUsrType;
    @XmlElement(name = "Section80U", required = true)
    protected BigInteger section80U;
    @XmlElement(name = "Section80RRB", required = true)
    protected BigInteger section80RRB;
    @XmlElement(name = "Section80QQB", required = true)
    protected BigInteger section80QQB;
    @XmlElement(name = "Section80CCG", required = true)
    protected BigInteger section80CCG;
    @XmlElement(name = "Section80TTA", required = true)
    protected BigInteger section80TTA;
    @XmlElement(name = "TotalChapVIADeductions", required = true)
    protected BigInteger totalChapVIADeductions;


    public BigInteger getSection80C() {
        return section80C;
    }

    public void setSection80C(BigInteger value) {
        this.section80C = value;
    }

    public BigInteger getSection80CCC() {
        return section80CCC;
    }

    public void setSection80CCC(BigInteger value) {
        this.section80CCC = value;
    }

    public BigInteger getSection80CCDEmployeeOrSE() {
        return section80CCDEmployeeOrSE;
    }

    public void setSection80CCDEmployeeOrSE(BigInteger value) {
        this.section80CCDEmployeeOrSE = value;
    }

    public BigInteger getSection80CCDEmployer() {
        return section80CCDEmployer;
    }

    public void setSection80CCDEmployer(BigInteger value) {
        this.section80CCDEmployer = value;
    }

    public BigInteger getSection80CCD1B() {
        return section80CCD1B;
    }

    public void setSection80CCD1B(BigInteger value) {
        this.section80CCD1B = value;
    }

   
    public BigInteger getSection80DD() {
        return section80DD;
    }

    public void setSection80DD(BigInteger value) {
        this.section80DD = value;
    }

    public BigInteger getSection80DDB() {
        return section80DDB;
    }

    public void setSection80DDB(BigInteger value) {
        this.section80DDB = value;
    }

    public BigInteger getSection80E() {
        return section80E;
    }

    public void setSection80E(BigInteger value) {
        this.section80E = value;
    }

    public BigInteger getSection80EE() {
        return section80EE;
    }

    public void setSection80EE(BigInteger value) {
        this.section80EE = value;
    }

    public BigInteger getSection80G() {
        return section80G;
    }

    public void setSection80G(BigInteger value) {
        this.section80G = value;
    }

    public BigInteger getSection80GG() {
        return section80GG;
    }

    public void setSection80GG(BigInteger value) {
        this.section80GG = value;
    }

    public BigInteger getSection80GGC() {
        return section80GGC;
    }

    public void setSection80GGC(BigInteger value) {
        this.section80GGC = value;
    }

    public BigInteger getSection80U() {
        return section80U;
    }

    public void setSection80U(BigInteger value) {
        this.section80U = value;
    }


    public BigInteger getSection80RRB() {
        return section80RRB;
    }

    public void setSection80RRB(BigInteger value) {
        this.section80RRB = value;
    }

    public BigInteger getSection80QQB() {
        return section80QQB;
    }


    public void setSection80QQB(BigInteger value) {
        this.section80QQB = value;
    }

    public BigInteger getSection80CCG() {
        return section80CCG;
    }


    public void setSection80CCG(BigInteger value) {
        this.section80CCG = value;
    }


    public BigInteger getSection80TTA() {
        return section80TTA;
    }


    public void setSection80TTA(BigInteger value) {
        this.section80TTA = value;
    }


    public BigInteger getTotalChapVIADeductions() {
        return totalChapVIADeductions;
    }

    public void setTotalChapVIADeductions(BigInteger value) {
        this.totalChapVIADeductions = value;
    }

	public String getSection80DDUsrType() {
		return section80DDUsrType;
	}

	public void setSection80DDUsrType(String section80ddUsrType) {
		section80DDUsrType = section80ddUsrType;
	}

	public String getSection80DDBUsrType() {
		return section80DDBUsrType;
	}

	public void setSection80DDBUsrType(String section80ddbUsrType) {
		section80DDBUsrType = section80ddbUsrType;
	}

	public String getSection80UUsrType() {
		return section80UUsrType;
	}

	public void setSection80UUsrType(String section80uUsrType) {
		section80UUsrType = section80uUsrType;
	}

	public Section80DHealthInsPremium getSection80DHealthInsPremium() {
		return section80DHealthInsPremium;
	}

	public void setSection80DHealthInsPremium(Section80DHealthInsPremium section80dHealthInsPremium) {
		section80DHealthInsPremium = section80dHealthInsPremium;
	}

    
}
